// Frontend permission helpers — UI gating only; backend is source of truth.

function hasPermission(user, permission) {
  if (!user) return false;
  if (user.role === 'super_admin') return true;
  const perms = user.permissions || [];
  if (perms.includes('*')) return true;
  return perms.includes(permission);
}

const PERMS = {
  USERS_VIEW: 'USERS_VIEW',
  USERS_CREATE: 'USERS_CREATE',
  USERS_EDIT: 'USERS_EDIT',
  USERS_DELETE: 'USERS_DELETE',
  CLIENTS_VIEW: 'CLIENTS_VIEW',
  CLIENTS_CREATE: 'CLIENTS_CREATE',
  CLIENTS_EDIT: 'CLIENTS_EDIT',
  CLIENTS_DELETE: 'CLIENTS_DELETE',
  CLIENTS_APPROVE: 'CLIENTS_APPROVE',
  CLIENTS_SUSPEND: 'CLIENTS_SUSPEND',
  PROJECTS_VIEW: 'PROJECTS_VIEW',
  PROJECTS_CREATE: 'PROJECTS_CREATE',
  PROJECTS_EDIT: 'PROJECTS_EDIT',
  PROJECTS_DELETE: 'PROJECTS_DELETE',
  LEADS_VIEW: 'LEADS_VIEW',
  LEADS_EDIT: 'LEADS_EDIT',
  LEADS_CONVERT: 'LEADS_CONVERT',
  CONTENT_VIEW: 'CONTENT_VIEW',
  CONTENT_EDIT: 'CONTENT_EDIT',
  CMS_VIEW: 'CMS_VIEW',
  CMS_EDIT: 'CMS_EDIT',
  CHAT_VIEW: 'CHAT_VIEW',
  CHAT_REPLY: 'CHAT_REPLY',
  SETTINGS_VIEW: 'SETTINGS_VIEW',
  SETTINGS_EDIT: 'SETTINGS_EDIT',
  INTEGRATIONS_VIEW: 'INTEGRATIONS_VIEW',
  INTEGRATIONS_EDIT: 'INTEGRATIONS_EDIT',
  WEBHOOKS_VIEW: 'WEBHOOKS_VIEW',
  WEBHOOKS_EDIT: 'WEBHOOKS_EDIT',
  ACTIVITY_VIEW: 'ACTIVITY_VIEW',
};

export { hasPermission, PERMS };
